name: CI
on:
  push:
  pull_request:
    branches:
      - !refs/heads/*
    tags:
      - !refs/tags/*
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Checkout code
      uses: actions/checkout@master

    - name: Download dependencies
      run: go mod download
      env:
        GOPROXY: https://proxy.golang.org

    - name: Build
      run: make build
      env:
        VERBOSE: 1

    - name: Unit tests
      run: make test
      env:
        VERBOSE: 1
        
    - name: Integration tests
      run: make test-integration
      env:
        VERBOSE: 1
        
    - name: Lint
      run: make lint

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@master

    - name: Build image
      run: docker build --build-arg GOPROXY=https://proxy.golang.org -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} .
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Tag image
      run: docker tag ${GITHUB_REPOSITORY}:${GITHUB_SHA} ${GITHUB_REPOSITORY}:${GITHUB_REF#"refs/heads/"}
      if: github.ref != '' && github.head_ref == ''
